In [1]:
import pandas as pd
import numpy as np

In [5]:
lend = pd.read_excel(r'C:\Users\rakes\Documents\Raq files\Data Science\Data sets\Lending Data.xlsx', engine='openpyxl')

C:\Users\bepec\anaconda3\lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")


In [6]:
lend.head()

Name of Lending Institution HQ State Rank TA Ratio1 TBL Ratio1  \
0                         NaN      NaN   -1        -2         -3   
1       American Express Co.       NY     1   0.23829   0.999544   
2    First Citizens Banchares      NC     2  0.187393    0.49083   
3    Wintrust Financial Corp.      IL     3  0.168999   0.383561   
4               Zions Bancorp      UT     4  0.117973   0.260577   

  Amount ($1,000)  Number      Lender Asset Size  Amount ($1,000).1  \
0              -4       -5                    -6               -7.0   
1        16350038  3603226  >$50B                        16318089.0   
2         3914507   117702  $10B-$50B                      378394.0   
3         2842793   136801  $10B-$50B                      800526.0   
4         6231770    52612  >$50B                          526206.0   

   Number .1  Unnamed: 10  Amount ($1,000).2  Number .2 CC Amount/TA1  
0       -8.0          NaN               -9.0      -10.0           -11  
1  3603088.0          NaN            31949.0      138.0          0.28  
2   105081.0          NaN          3536113.0    12621.0           .    
3   126455.0          NaN          2042267.0    10346.0             0  
4    32973.0          NaN          5705564.0    19639.0             0

In [7]:
lend.tail()

Name of Lending Institution HQ State Rank TA Ratio1  \
92                     Charles Schwab Bk                    NV   NR         -   
93                     Third FS&LA                          OH   NR         -   
94  *The bank was formerly known as GE Money Bank,...      NaN  NaN       NaN   
95  1 TA = total domestic assets held by the lende...      NaN  NaN       NaN   
96  Source: U.S. Small Business Administration, Of...      NaN  NaN       NaN   

   TBL Ratio1 Amount ($1,000) Number      Lender Asset Size  \
92          -               -       -  >$10B                  
93          -               -       -  >$10B                  
94        NaN             NaN     NaN                   NaN   
95        NaN             NaN     NaN                   NaN   
96        NaN             NaN     NaN                   NaN   

    Amount ($1,000).1  Number .1  Unnamed: 10  Amount ($1,000).2  Number .2  \
92                0.0        0.0          NaN                0.0        0.0   
93                0.0        0.0          NaN                0.0        0.0   
94                NaN        NaN          NaN                NaN        NaN   
95                NaN        NaN          NaN                NaN        NaN   
96                NaN        NaN          NaN                NaN        NaN   

   CC Amount/TA1  
92           .    
93           .    
94           NaN  
95           NaN  
96           NaN

In [5]:
lend.shape

(97, 14)

In [4]:
lend.isnull().sum()

Name of Lending Institution     1
HQ State                        4
Rank                            3
TA Ratio1                       3
TBL Ratio1                      3
Amount ($1,000)                 3
Number                          3
Lender Asset Size               3
Amount ($1,000).1               3
Number .1                       3
Unnamed: 10                    97
Amount ($1,000).2               3
Number .2                       3
CC Amount/TA1                   3
dtype: int64

In [7]:
del lend['Unnamed: 10']

In [8]:
lend.isnull().sum()

Name of Lending Institution    1
HQ State                       4
Rank                           3
TA Ratio1                      3
TBL Ratio1                     3
Amount ($1,000)                3
Number                         3
Lender Asset Size              3
Amount ($1,000).1              3
Number .1                      3
Amount ($1,000).2              3
Number .2                      3
CC Amount/TA1                  3
dtype: int64

# Clean Rank with value 0

In [9]:
lend['Rank'].unique()

array([-1, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 13, 15, 16, 17, 18, 19, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 'NR', nan],
      dtype=object)

In [10]:
lend['Rank'] = lend['Rank'].replace('NR', 0)


In [11]:
lend['Rank'].unique()

array([-1.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10., 11., 13., 15.,
       16., 17., 18., 19., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 36., 37., 38., 39., 40., 42., 43., 44., 45.,
       46., 47., 48., 49., 50., 51., 52., 53., 54., 55., 56., 57., 58.,
       59., 60., 61., 62., 63., 64., 65., 66., 67., 69., 70., 71., 72.,
       73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83., 84., 85.,
       86., 87., 88.,  0., nan])

In [12]:
lend = lend.dropna()

In [13]:
lend.isnull().sum()

Name of Lending Institution    0
HQ State                       0
Rank                           0
TA Ratio1                      0
TBL Ratio1                     0
Amount ($1,000)                0
Number                         0
Lender Asset Size              0
Amount ($1,000).1              0
Number .1                      0
Amount ($1,000).2              0
Number .2                      0
CC Amount/TA1                  0
dtype: int64

# clean '-' values with column mean

In [15]:
lend = lend.replace('-', np.nan)

In [16]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 93 entries, 1 to 93
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Name of Lending Institution  93 non-null     object 
 1   HQ State                     93 non-null     object 
 2   Rank                         93 non-null     float64
 3   TA Ratio1                    89 non-null     float64
 4   TBL Ratio1                   88 non-null     float64
 5   Amount ($1,000)              89 non-null     float64
 6   Number                       89 non-null     float64
 7   Lender Asset Size            93 non-null     object 
 8   Amount ($1,000).1            93 non-null     float64
 9   Number .1                    93 non-null     float64
 10  Amount ($1,000).2            93 non-null     float64
 11  Number .2                    93 non-null     float64
 12  CC Amount/TA1                93 non-null     object 
dtypes: float64(9), object(

In [21]:
lend = lend.fillna(lend.mean())

In [22]:
lend

Name of Lending Institution HQ State  Rank  TA Ratio1  TBL Ratio1  \
1               American Express Co.       NY    1.0   0.238290    0.999544   
2            First Citizens Banchares      NC    2.0   0.187393    0.490830   
3            Wintrust Financial Corp.      IL    3.0   0.168999    0.383561   
4                       Zions Bancorp      UT    4.0   0.117973    0.260577   
5             Synovus Financial Corp.      GA    5.0   0.162333    0.381387   
..                                ...      ...   ...        ...         ...   
89  USAA Svg. Bank                          NV   0.0   0.000000    0.251196   
90                State Street Corp.       MA    0.0   0.048668    0.251196   
91     E Trade Bk                           VA   0.0   0.048668    0.251196   
92     Charles Schwab Bk                    NV   0.0   0.048668    0.251196   
93     Third FS&LA                          OH   0.0   0.048668    0.251196   

    Amount ($1,000)       Number      Lender Asset Size  Amount ($1,000).1  \
1      1.635004e+07  3.603226e+06  >$50B                        16318089.0   
2      3.914507e+06  1.177020e+05  $10B-$50B                      378394.0   
3      2.842793e+06  1.368010e+05  $10B-$50B                      800526.0   
4      6.231770e+06  5.261200e+04  >$50B                          526206.0   
5      4.227168e+06  2.267500e+04  $10B-$50B                      539666.0   
..              ...           ...                   ...                ...   
89     0.000000e+00  1.000000e+00  >$10B                               0.0   
90     3.184791e+06  2.164190e+05  >$50B                               0.0   
91     3.184791e+06  2.164190e+05  >$10B                               0.0   
92     3.184791e+06  2.164190e+05  >$10B                               0.0   
93     3.184791e+06  2.164190e+05  >$10B                               0.0   

    Number .1  Amount ($1,000).2  Number .2 CC Amount/TA1  
1   3603088.0            31949.0      138.0          0.28  
2    105081.0          3536113.0    12621.0           .    
3    126455.0          2042267.0    10346.0             0  
4     32973.0          5705564.0    19639.0             0  
5      9593.0          3687502.0    13082.0          0.01  
..        ...                ...        ...           ...  
89        1.0                0.0        0.0           .    
90        0.0                0.0        0.0             0  
91        0.0                0.0        0.0           .    
92        0.0                0.0        0.0           .    
93        0.0                0.0        0.0           .    

[93 rows x 13 columns]

# clean '.' with column mean

In [25]:
lend = lend.replace('    .  ', np.nan)

In [26]:
lend['CC Amount/TA1'].unique()

array([0.28,  nan, 0.  , 0.01, 0.25, 0.05, 0.06, 0.1 , 0.03, 0.07, 0.02])

In [27]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 93 entries, 1 to 93
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Name of Lending Institution  93 non-null     object 
 1   HQ State                     93 non-null     object 
 2   Rank                         93 non-null     float64
 3   TA Ratio1                    93 non-null     float64
 4   TBL Ratio1                   93 non-null     float64
 5   Amount ($1,000)              93 non-null     float64
 6   Number                       93 non-null     float64
 7   Lender Asset Size            93 non-null     object 
 8   Amount ($1,000).1            93 non-null     float64
 9   Number .1                    93 non-null     float64
 10  Amount ($1,000).2            93 non-null     float64
 11  Number .2                    93 non-null     float64
 12  CC Amount/TA1                46 non-null     float64
dtypes: float64(10), object

In [28]:
lend['CC Amount/TA1'] = lend['CC Amount/TA1'].fillna(lend['CC Amount/TA1'].mean())

In [29]:
lend['CC Amount/TA1'].unique()

array([0.28      , 0.02086957, 0.        , 0.01      , 0.25      ,
       0.05      , 0.06      , 0.1       , 0.03      , 0.07      ,
       0.02      ])

# Convert lending assets size = categaory like 0,1,2 etc based on levels available

In [30]:
lend.head()

Name of Lending Institution HQ State  Rank  TA Ratio1  TBL Ratio1  \
1       American Express Co.       NY    1.0   0.238290    0.999544   
2    First Citizens Banchares      NC    2.0   0.187393    0.490830   
3    Wintrust Financial Corp.      IL    3.0   0.168999    0.383561   
4               Zions Bancorp      UT    4.0   0.117973    0.260577   
5     Synovus Financial Corp.      GA    5.0   0.162333    0.381387   

   Amount ($1,000)    Number      Lender Asset Size  Amount ($1,000).1  \
1       16350038.0  3603226.0  >$50B                        16318089.0   
2        3914507.0   117702.0  $10B-$50B                      378394.0   
3        2842793.0   136801.0  $10B-$50B                      800526.0   
4        6231770.0    52612.0  >$50B                          526206.0   
5        4227168.0    22675.0  $10B-$50B                      539666.0   

   Number .1  Amount ($1,000).2  Number .2  CC Amount/TA1  
1  3603088.0            31949.0      138.0        0.28000  
2   105081.0          3536113.0    12621.0        0.02087  
3   126455.0          2042267.0    10346.0        0.00000  
4    32973.0          5705564.0    19639.0        0.00000  
5     9593.0          3687502.0    13082.0        0.01000

In [31]:
lend['Lender Asset Size'].unique()

array(['>$50B               ', '$10B-$50B           ',
       '>$10B               '], dtype=object)

In [32]:
lend['Lender Asset Size'] = lend['Lender Asset Size'].replace(['>$50B               ', '$10B-$50B           ',
       '>$10B               '], [2,1, 0])

In [33]:
lend.head()

Name of Lending Institution HQ State  Rank  TA Ratio1  TBL Ratio1  \
1       American Express Co.       NY    1.0   0.238290    0.999544   
2    First Citizens Banchares      NC    2.0   0.187393    0.490830   
3    Wintrust Financial Corp.      IL    3.0   0.168999    0.383561   
4               Zions Bancorp      UT    4.0   0.117973    0.260577   
5     Synovus Financial Corp.      GA    5.0   0.162333    0.381387   

   Amount ($1,000)    Number   Lender Asset Size  Amount ($1,000).1  \
1       16350038.0  3603226.0                  2         16318089.0   
2        3914507.0   117702.0                  1           378394.0   
3        2842793.0   136801.0                  1           800526.0   
4        6231770.0    52612.0                  2           526206.0   
5        4227168.0    22675.0                  1           539666.0   

   Number .1  Amount ($1,000).2  Number .2  CC Amount/TA1  
1  3603088.0            31949.0      138.0        0.28000  
2   105081.0          3536113.0    12621.0        0.02087  
3   126455.0          2042267.0    10346.0        0.00000  
4    32973.0          5705564.0    19639.0        0.00000  
5     9593.0          3687502.0    13082.0        0.01000

In [ ]:
# from sklearn.preprocessing import LabelEncoder
# label_encoder = LabelEncoder()
# encoded = label_encoder.fit(lend['Lender Asset Size'])
# lend['Lender Asset Size'] = encoded.tranform(lend['Lender Asset Size'])

# convert to csv 

In [40]:
lend.to_csv(r"C:\Users\bepec\desktop\lend.csv", index=False)


In [38]:
cd

C:\Users\bepec


In [39]:
cd desktop

C:\Users\bepec\desktop
