In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv("student.csv")
data.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [2]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [3]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.7966607763812839


In [4]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 5.41328614 13.7915068   5.58201615  8.65058913 13.7915068 ]
 [ 5.41328614  5.41328614  5.58201615  8.65058913 14.64280278]
 [11.35883762  8.5030114   5.58201615  6.76206178  9.44844012]
 ...
 [ 9.44844012  8.5030114   4.47935206  6.76206178  6.76206178]
 [ 9.65233765 18.13250708  4.47935206  8.65058913  8.65058913]
 [ 8.5030114   9.95324274  4.47935206  8.65058913  5.41328614]] [[[ 7  6  1  0  0]
  [12 14  1  0  0]
  [ 7  6  2  0 10]
  [10  9  2  0  0]
  [12 14  1  0  0]]

 [[ 7  6  1  0  0]
  [ 7  6  1  0  0]
  [ 7  6  2  0 10]
  [10  9  2  0  0]
  [11 15  1  0  2]]

 [[ 9 12  3  0  3]
  [10  9  4  0  0]
  [ 7  6  2  0 10]
  [10  8  1  3  3]
  [ 8 10  2  0  6]]

 ...

 [[ 8 10  2  0  6]
  [10  9  4  0  0]
  [ 6  5  1  0  7]
  [10  8  1  3  3]
  [10  8  1  3  3]]

 [[10 10  2  0  2]
  [16 18  2  0  0]
  [ 6  5  1  0  7]
  [10  9  2  0  0]
  [10  9  2  0  0]]

 [[10  9  4  0  0]
  [12 10  2  0  2]
  [ 6  5  1  0  7]
  [10  9  2  0  0]
  [ 7  6  1  0  0]]] [array([[ 0, 15,  6,  0, 15]